# Generated by Django 2.2 on 2022-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220614_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='books_borrowed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='branch',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
