# Generated by Django 2.2 on 2022-06-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220615_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='books_borrowed_count',
            field=models.IntegerField(),
        ),
    ]
